program Client;

uses
  Forms,
  Unit2 in 'Unit2.pas' {Form2},
  ClientClassesUnit1 in 'ClientClassesUnit1.pas',
  Frame_Buttons in 'Frame_Buttons.pas' {FrameButtons: TFrame},
  FrameButtons2 in 'FrameButtons2.pas' {FrameButton2: TFrame},
  frm_ReporteAnalisis in 'frm_ReporteAnalisis.pas' {frmReporteAnalisis},
  UFrmParamsConfig in 'UFrmParamsConfig.pas' {FrmParamsConfig},
  UnitTCifrador in 'UnitTCifrador.pas',
  UfrmAutentic in 'UfrmAutentic.pas' {frmAutentic},
  Frm_Conectando in 'Frm_Conectando.pas' {FrmConectando},
  Frm_SelDatabase in 'Frm_SelDatabase.pas' {FrmSelDataBase},
  frm_ModificaBase in 'frm_ModificaBase.pas' {FrmModificaBase},
  frm_Login in 'frm_Login.pas' {frmLogin},
  frm_Configuracion in 'frm_Configuracion.pas' {FrmConfiguracion},
  UTFrmDatosCatalogo in 'UTFrmDatosCatalogo.pas' {FrmDatosCatalogo},
  UTFrmCatalogo in 'UTFrmCatalogo.pas' {FrmCatalogo},
  xDatabase in 'xDatabase.pas',
  UTFrmDatosSubgrupos in 'UTFrmDatosSubgrupos.pas' {FrmDatosSubgrupos},
  UTFrmGrupos in 'UTFrmGrupos.pas' {FrmGrupos},
  UTFrmDatosGrupos in 'UTFrmDatosGrupos.pas' {FrmDatosGrupos},
  UTFrmDisciplinas in 'UTFrmDisciplinas.pas' {FrmDisciplinas},
  UTFrmTransportes in 'UTFrmTransportes.pas' {FrmTransportes},
  UTFrmLugares in 'UTFrmLugares.pas' {FrmLugares},
  UTFrmDatosTransportes in 'UTFrmDatosTransportes.pas' {FrmDatosTransportes},
  UTFrmDatosDisciplinas in 'UTFrmDatosDisciplinas.pas' {FrmDatosDisciplinas},
  UTFrmDatosLugares in 'UTFrmDatosLugares.pas' {FrmDatosLugares},
  UTfrmUnidades in 'UTfrmUnidades.pas' {FrmUnidades},
  UTfrmDatosUnidades in 'UTfrmDatosUnidades.pas' {FrmDatosUnidades},
  UTFrmMonedas in 'UTFrmMonedas.pas' {FrmMonedas},
  UTFrmDatosMonedas in 'UTFrmDatosMonedas.pas' {FrmDatosMonedas},
  UTFrmEsquema in 'UTFrmEsquema.pas' {FrmEsquema},
  UTFrmOrganigrama in 'UTFrmOrganigrama.pas' {FrmOrganigrama},
  UTFrmDatosOrganigrama in 'UTFrmDatosOrganigrama.pas' {FrmDatosOrganigrama},
  UTFrmSeleccion in 'UTFrmSeleccion.pas' {FrmSeleccion},
  UTFrmMuestraAccesos in 'UTFrmMuestraAccesos.pas' {FrmMuestraAccesos},
  UTFrmArbolAccesos in 'UTFrmArbolAccesos.pas' {FrmArbolAccesos},
  UTFrmNiveles in 'UTFrmNiveles.pas' {FrmNiveles},
  UTFrmDatosNiveles in 'UTFrmDatosNiveles.pas' {FrmDatosNiveles},
  UTFrmDepartamentos in 'UTFrmDepartamentos.pas' {FrmDepartamentos},
  UTFrmDatosDepartamento in 'UTFrmDatosDepartamento.pas' {FrmDatosDepartamento},
  UTFrmTipoTransporte in 'UTFrmTipoTransporte.pas' {FrmTipoTransporte},
  UTFrmDatosTipoTransporte in 'UTFrmDatosTipoTransporte.pas' {FrmDatosTipoTransporte},
  UTFrmUsuarios in 'UTFrmUsuarios.pas' {FrmUsuarios},
  UTFrmDatosUsuarios in 'UTFrmDatosUsuarios.pas' {FrmDatosUsuarios},
  UTFrmRoles in 'UTFrmRoles.pas' {FrmRoles},
  UTfrmDatosRoles in 'UTfrmDatosRoles.pas' {FrmDatosRoles},
  UTFrmPermisoRol in 'UTFrmPermisoRol.pas' {FrmPermisoRol},
  UTFrmPermisoUsuario in 'UTFrmPermisoUsuario.pas' {FrmPermisoUsuario},
  UTFrmPais in 'UTFrmPais.pas' {FrmPais},
  UTFrmCatalogoDoc in 'UTFrmCatalogoDoc.pas' {FrmCatalogoDoc},
  UTFrmDetalleDocs in 'UTFrmDetalleDocs.pas' {FrmDetalleDocs},
  UTFrmPartidaDoc in 'UTFrmPartidaDoc.pas' {FrmPartidaDoc},
  UTFrmCiudad in 'UTFrmCiudad.pas' {FrmCiudad},
  UTFrmEstado in 'UTFrmEstado.pas' {FrmEstado},
  UTFrmDatosPais in 'UTFrmDatosPais.pas' {FrmDatosPais},
  UTFrmDatosCiudad in 'UTFrmDatosCiudad.pas' {FrmDatosCiudad},
  UTFrmDatosEstado in 'UTFrmDatosEstado.pas' {FrmDatosEstado},
  UTFrmContacto in 'UTFrmContacto.pas' {FrmContacto},
  UTFrmDatosContacto in 'UTFrmDatosContacto.pas' {FrmDatosContacto},
  Unit3 in 'Unit3.pas' {Form3},
  UTFrmFirmantes in 'UTFrmFirmantes.pas' {FrmFirmantes},
  UTFrmDatosFirmante in 'UTFrmDatosFirmante.pas' {FrmDatosFirmante},
  UTFrmDocumentos in 'UTFrmDocumentos.pas' {FrmDocumentos},
  UTFrmDatosDocumentos in 'UTFrmDatosDocumentos.pas' {FrmDatosDocumento},
  UTFrmPeriodoFirmante in 'UTFrmPeriodoFirmante.pas' {FrmPeriodoFirmante},
  UTFrmDatosPeriodo in 'UTFrmDatosPeriodo.pas' {FrmDatosPeriodo},
  UTFrmConfFirmantes in 'UTFrmConfFirmantes.pas' {FrmConfFirmantes},
  UTFrmDatosConfFirmante in 'UTFrmDatosConfFirmante.pas' {FrmDatosConfFirmante},
  UTFrmImportarExcel in 'UTFrmImportarExcel.pas' {FrmImportarExcel},
  UTFrmNivelPorUsuario in 'UTFrmNivelPorUsuario.pas' {FrmNivelPorUsuario},
  UTFrmTipoMovimiento in 'UTFrmTipoMovimiento.pas' {FrmTipoMovimiento},
  UTFrmDatosTipoMovimiento in 'UTFrmDatosTipoMovimiento.pas' {FrmDatosTipoMovimiento},
  alm_genericclasses in 'alm_genericclasses.pas',
  UTFrmMovimientosDetalle in 'UTFrmMovimientosDetalle.pas' {FrmMovimientosDetalle},
  UTFrmMovimientos in 'UTFrmMovimientos.pas' {FrmMovimientos},
  UTFrmMovimientosPartida in 'UTFrmMovimientosPartida.pas' {FrmPartidaMovimientos},
  UTFrmFormaPago in 'UTFrmFormaPago.pas' {FrmFormaPago},
  UTFrmDetalleSubgrupo in 'UTFrmDetalleSubgrupo.pas' {FrmDetalleSubgrupo},
  UTFrmSubgrupos in 'UTFrmSubgrupos.pas' {FrmSubgrupos},
  UTFrmDatosDetalleSubgrupo in 'UTFrmDatosDetalleSubgrupo.pas' {FrmDatosDetalleSubgrupo},
  UTFrmEspecificaciones in 'UTFrmEspecificaciones.pas' {FrmEspecificaciones},
  UTFrmOrdenarEsp in 'UTFrmOrdenarEsp.pas' {FrmOrdenarEsp},
  UTFrmSuite in 'UTFrmSuite.pas' {FrmSuite},
  UTFrmDatosObras in 'Subsistema GDP\UTFrmDatosObras.pas' {FrmDatosObras},
  UTFrmDatosReprogramaciones in 'Subsistema GDP\UTFrmDatosReprogramaciones.pas' {FrmDatosReprogramaciones},
  UTFrmDatosTiposReprogramaciones in 'Subsistema GDP\UTFrmDatosTiposReprogramaciones.pas' {FrmDatosTiposReprogramaciones},
  UTFrmEstimaciones in 'Subsistema GDP\UTFrmEstimaciones.pas' {FrmEstimaciones},
  UTFrmEstimacionesDetalles in 'Subsistema GDP\UTFrmEstimacionesDetalles.pas' {FrmEstimacionesDetalles},
  UTFrmEstimacionesPartidas in 'Subsistema GDP\UTFrmEstimacionesPartidas.pas' {FrmEstimacionesPartidas},
  UTFrmGrabage in 'Subsistema GDP\UTFrmGrabage.pas' {Form4},
  UTFrmObras in 'Subsistema GDP\UTFrmObras.pas' {FrmObras},
  UTFrmReprogramaciones in 'Subsistema GDP\UTFrmReprogramaciones.pas' {FrmReprogramaciones},
  UTFrmForm in 'Subsistema GDP\UTFrmForm.pas' {FrmForm},
  UTFrmTiposReprogramaciones in 'Subsistema GDP\UTFrmTiposReprogramaciones.pas' {FrmTiposReprogramaciones},
  UTFrmDatosForm in 'Subsistema GDP\UTFrmDatosForm.pas' {FrmDatosForm},
  UTFrmTiposestimacion in 'Subsistema GDP\UTFrmTiposestimacion.pas' {FrmTiposestimacion},
  UTFrmDatosTiposestimacion in 'Subsistema GDP\UTFrmDatosTiposestimacion.pas' {FrmDatosTiposestimacion},
  UTFrmSeleccionDX in 'UTFrmSeleccionDX.pas' {FrmSeleccionDX},
  UTFrmPrincipalTic in 'Subsistema TIC\UTFrmPrincipalTic.pas' {FrmPrincipalTic},
  UTFrmDatosPersonal in 'Subsistema RHH\UTFrmDatosPersonal.pas' {FrmDatosPersonal},
  Frm_SelPeriodo in 'Frm_SelPeriodo.pas' {FrmSelPeriodo},
  UTFrmPermisosRol2 in 'UTFrmPermisosRol2.pas' {FrmPermisosRol},
  ExportaExcel in 'ExportaExcel.pas',
  frm_SelectSheet in 'frm_SelectSheet.pas' {frmSelectSheet},
  UTFrmSelFormato in 'UTFrmSelFormato.pas' {FrmSelFormato},
  UTFrmImpuestos in 'UTFrmImpuestos.pas' {FrmImpuesto},
  UTFrmManttoPrev in 'UTFrmManttoPrev.pas' {FrmManttoPrev},
  UTFrmDatosManttoPrev in 'UTFrmDatosManttoPrev.pas' {FrmDatosManttoPrev},
  UTFrmSolicitaPersonal in 'UTFrmSolicitaPersonal.pas' {FrmSolicitaPersonal},
  UTFrmVentanaPrincipalTIC in 'Subsistema TIC\UTFrmVentanaPrincipalTIC.pas' {FrmVentanaPrincipalTIC},
  UTFrmMantenimientos in 'Subsistema TIC\UTFrmMantenimientos.pas' {FrmMantenimientos},
  UTFrmVerMantto in 'Subsistema TIC\UTFrmVerMantto.pas' {FrmVerMantto},
  UTFrmPersonalRhh in 'Subsistema RHH\UTFrmPersonalRhh.pas' {FrmPersonalRhh},
  UTFrmCatalogoBancos in 'Subsistema CONT\UTFrmCatalogoBancos.pas' {FrmCatalogoBancos},
  UTFrmDatosBancos in 'Subsistema CONT\UTFrmDatosBancos.pas' {FrmDatosBancos},
  UTFrmDatosSalarios in 'Subsistema RHH\UTFrmDatosSalarios.pas' {FrmDatosSalarios},
  UTFrmCatalogoCuentasContables in 'Subsistema RHH\UTFrmCatalogoCuentasContables.pas' {FrmCatalogoCuentasContables},
  UTFrmDatosCuentasContables in 'Subsistema RHH\UTFrmDatosCuentasContables.pas' {FrmDatosCuentasContables},
  UTFrmSelPersonal in 'Subsistema PRUEBAS\UTFrmSelPersonal.pas' {FrmSelPersonal},
  UTFrmDatosDocumentosPersonal in 'Subsistema RHH\UTFrmDatosDocumentosPersonal.pas' {FrmDatosDocumentosPersonal},
  UTFfrmAltaModDocumentos in 'Subsistema RHH\UTFfrmAltaModDocumentos.pas' {FrmAltaModDocumentos},
  UTFrmCargaImagen in 'UTFrmCargaImagen.pas' {FrmCargaImagen},
  UInfoPanel in 'UInfoPanel.pas' {InfoPanel},
  UTFrmListaModSal in 'Subsistema RHH\UTFrmListaModSal.pas' {FrmListaModSal},
  UTFrmHistorialSalario in 'Subsistema RHH\UTFrmHistorialSalario.pas' {FrmHistorialSalario},
  Direct3D9 in 'DirectX\Direct3D9.pas',
  DirectDraw in 'DirectX\DirectDraw.pas',
  DirectShow9 in 'DirectX\DirectShow9.pas',
  DirectSound in 'DirectX\DirectSound.pas',
  DXTypes in 'DirectX\DXTypes.pas',
  VFrames in 'VFrames.pas',
  Frame_Video in 'Frame_Video.pas' {Frame1: TFrame},
  UtfrmTratamiento in 'Subsistema RHH\UtfrmTratamiento.pas' {FrmTratamiento},
  UTFrmDatosTratamiento in 'Subsistema RHH\UTFrmDatosTratamiento.pas' {FrmDatosTratamiento},
  UTFrmGrado in 'Subsistema RHH\UTFrmGrado.pas' {FrmGrado},
  UTFrmDatosGrado in 'Subsistema RHH\UTFrmDatosGrado.pas' {FrmDatosGrado},
  UtfrmEstructuraO in 'Subsistema RHH\UtfrmEstructuraO.pas' {FrmEstructuraO},
  UTFrmDocumento in 'Subsistema RHH\UTFrmDocumento.pas' {FrmDocumento},
  UTFrmDatosDocumento in 'Subsistema RHH\UTFrmDatosDocumento.pas' {FrmDatosDocuumento},
  UTFrmModificacionInsumo in 'Subsistema TIC\UTFrmModificacionInsumo.pas' {FrmModificacionInsumo},
  Collections.Bags in 'Collections\Collections.Bags.pas',
  Collections.Base in 'Collections\Collections.Base.pas',
  Collections.BidiDictionaries in 'Collections\Collections.BidiDictionaries.pas',
  Collections.BidiMaps in 'Collections\Collections.BidiMaps.pas',
  Collections.Dictionaries in 'Collections\Collections.Dictionaries.pas',
  Collections.Dynamic in 'Collections\Collections.Dynamic.pas',
  Collections.Lists in 'Collections\Collections.Lists.pas',
  Collections.MultiMaps in 'Collections\Collections.MultiMaps.pas',
  Collections.Queues in 'Collections\Collections.Queues.pas',
  Collections.Sets in 'Collections\Collections.Sets.pas',
  Collections.Stacks in 'Collections\Collections.Stacks.pas',
  DMTicRepModuleUnit in 'Subsistema TIC\DMTicRepModuleUnit.pas' {TicRepModuleUnit: TDataModule},
  UTFrmAsignacionesPersonalTic in 'Subsistema TIC\UTFrmAsignacionesPersonalTic.pas' {FrmAsignacionesPersonalTic},
  UTFrmAsignacionIndividualTIC in 'Subsistema TIC\UTFrmAsignacionIndividualTIC.pas' {FrmAsignacionIndividualTIC},
  UTFrmCriteriosBusqeudaTic in 'Subsistema TIC\UTFrmCriteriosBusqeudaTic.pas' {FrmCriteriosBusqeudaTic},
  UTFrmMantenimientosTIC in 'Subsistema TIC\UTFrmMantenimientosTIC.pas' {FrmMantenimientosTIC},
  UTFrmDevolucionesGeneral in 'Subsistema TIC\UTFrmDevolucionesGeneral.pas' {FrmDevolucionesGeneral},
  UTFrmAsignarInsumosTic in 'Subsistema TIC\UTFrmAsignarInsumosTic.pas' {FrmAsignarInsumosTic},
  UTFrmDiagramaOrg in 'Subsistema RHH\UTFrmDiagramaOrg.pas' {FrmDiagramaOrg},
  UTFrmDatosDepartamentoDiag in 'Subsistema RHH\UTFrmDatosDepartamentoDiag.pas' {FrmDatosDeptoDiag},
  UTFrmPlazaRhu in 'Subsistema RHH\UTFrmPlazaRhu.pas' {FrmPlazaRhu},
  UTFrmPlazaRhuDetalle in 'Subsistema RHH\UTFrmPlazaRhuDetalle.pas' {FrmPlazaRhuDetalle},
  UTFrmGrupoPlazas in 'Subsistema RHH\UTFrmGrupoPlazas.pas' {FrmGrupoPlazas},
  rhh_genericclasses in 'Subsistema RHH\rhh_genericclasses.pas',
  nuc_genericclasses in 'nuc_genericclasses.pas',
  UTFrmCuantos in 'Subsistema RHH\UTFrmCuantos.pas' {FrmCuantos},
  UTFrmCancelarPlazas in 'Subsistema RHH\UTFrmCancelarPlazas.pas' {FrmCancelarPlazas},
  UTFrmEspecificacionesDX in 'Subsistema TIC\UTFrmEspecificacionesDX.pas' {FrmEspecificacionesDX},
  UtFrmDisciplinasDatosDX in 'Subsistema TIC\UtFrmDisciplinasDatosDX.pas' {FrmDisciplinasDatosDX},
  UtFrmGruposDatosDX in 'Subsistema TIC\UtFrmGruposDatosDX.pas' {FrmGruposDatosDX},
  UtFrmSubgruposDatosDX in 'Subsistema TIC\UtFrmSubgruposDatosDX.pas' {FrmSubgruposDatosDX},
  UTFrmespecdetallesubgrupo in 'Subsistema TIC\UTFrmespecdetallesubgrupo.pas' {FrmEspecDetalleSubgrupo},
  UTFrmFichaPersonal in 'Subsistema RHH\UTFrmFichaPersonal.pas' {FrmFichaPersonal},
  UTFrmCatalogoPersonal in 'Subsistema RHH\UTFrmCatalogoPersonal.pas' {FrmCatalogoPersonal},
  UTFrmAnalizaPerfiles in 'Subsistema RHH\UTFrmAnalizaPerfiles.pas' {FrmAnalizaPerfiles},
  UTFrmFiltroPostulante in 'Subsistema RHH\UTFrmFiltroPostulante.pas' {FrmFiltroPostulante},
  UTFrmEspecificaciones_MadosaDX in 'Subsistema TIC\UTFrmEspecificaciones_MadosaDX.pas' {FrmEspecificaciones_MadosaDX},
  UTFrmEspecfificaciones_MadosaDatosDX in 'Subsistema TIC\UTFrmEspecfificaciones_MadosaDatosDX.pas' {FrmEspecificaciones_MadosaDatosDX},
  UtFrmEditPlazaDetalle in 'Subsistema RHH\UtFrmEditPlazaDetalle.pas' {FrmEditPlazaDetalle},
  ClientModuleUnit1 in 'ClientModuleUnit1.pas' {ClientModule1: TDataModule},
  UTFrmSolicitarVacante in 'Subsistema RHH\UTFrmSolicitarVacante.pas' {FrmSolicitarVacante},
  UTFrmTipoRecursos in 'UTFrmTipoRecursos.pas' {FrmTipoRecursos},
  UTFrmDatosTipoRecursos in 'UTFrmDatosTipoRecursos.pas' {FrmDatosTipoRecursos},
  UTFrmSelSubgrupo in 'UTFrmSelSubgrupo.pas' {FrmSelSubgrupo},
  UTFrmSalariosCatalogo in 'Subsistema RHH\UTFrmSalariosCatalogo.pas' {FrmSalariosCatalogo},
  UTFrmNuevoSalario in 'Subsistema RHH\UTFrmNuevoSalario.pas' {FrmNuevoSalario},
  UTFrmModificacionSalario in 'Subsistema RHH\UTFrmModificacionSalario.pas' {FrmModificacionSalario},
  UTFrmOrganizacion in 'UTFrmOrganizacion.pas' {FrmOrganizacion},
  UTFrmSeleccionaOrganizacion in 'Subsistema GDP\UTFrmSeleccionaOrganizacion.pas' {FrmSeleccionaOrganizacion},
  UTFrmFichaDepartamento in 'Subsistema RHH\UTFrmFichaDepartamento.pas' {FrmFichaDepartamento},
  UTFrmNewItem in 'UTFrmNewItem.pas' {FrmNewItem},
  UTFrmEstadoModificacion in 'Subsistema RHH\UTFrmEstadoModificacion.pas' {FrmEstadoModificacion},
  UtFrmAsignacionDePostulantes in 'Subsistema RHH\UtFrmAsignacionDePostulantes.pas' {FrmAsignacionDePostulantes},
  UTFrmCargosxConvenio in 'Subsistema RHH\UTFrmCargosxConvenio.pas' {FrmCargosxConvenio},
  UTFrmAgregarConcepto in 'Subsistema RHH\UTFrmAgregarConcepto.pas' {FrmAgregarConcepto},
  UTFrmAltaModDocumentos in 'Subsistema RHH\UTFrmAltaModDocumentos.pas',
  UTFrmDatosBancarios in 'Subsistema RHH\UTFrmDatosBancarios.pas' {FrmDatosBancarios},
  UTFrmDocumentosPersonal in 'Subsistema RHH\UTFrmDocumentosPersonal.pas' {FrmDocumentosPersonal},
  UtFrmAltaExperiencia in 'Subsistema RHH\UtFrmAltaExperiencia.pas' {FrmAltaExperiencia},
  UTFrmSelCargoxConvenio in 'Subsistema RHH\UTFrmSelCargoxConvenio.pas' {FrmSelCargoxConvenio},
  UTfrmConsultaPlazaDX in 'Subsistema RHH\UTfrmConsultaPlazaDX.pas' {FrmConsultaPlazaDX},
  UtfrmAltaDocumentosApirante in 'Subsistema RHH\UtfrmAltaDocumentosApirante.pas' {frmAltaDocumentosApirante},
  UTFrmConsumoxArticulo in 'Subsistema TIC\UTFrmConsumoxArticulo.pas' {FrmConsumoxArticulo},
  UTFrmAlmacen in 'Subsistema ALM\UTFrmAlmacen.pas' {FrmAlmacen},
  UTFrmArticulo2 in 'Subsistema ALM\UTFrmArticulo2.pas' {FrmArticulo2},
  UTFrmAsignarComprador in 'Subsistema ALM\UTFrmAsignarComprador.pas' {FrmAsignarComprador},
  UTFrmAsignarProveedor in 'Subsistema ALM\UTFrmAsignarProveedor.pas' {FrmAsignarProveedor},
  UTFrmCantidadSalida in 'Subsistema ALM\UTFrmCantidadSalida.pas' {FrmCantidadSalida},
  UTFrmCotizacionCaptura in 'Subsistema ALM\UTFrmCotizacionCaptura.pas' {FrmCotizacionCaptura},
  UTFrmCotizacionDetalle in 'Subsistema ALM\UTFrmCotizacionDetalle.pas' {FrmCotizacionDetalle},
  UTFrmCotizaciones in 'Subsistema ALM\UTFrmCotizaciones.pas' {FrmCotizaciones},
  UTFrmCotizacionPartida in 'Subsistema ALM\UTFrmCotizacionPartida.pas' {FrmCotizacionPartida},
  UTFrmCotizador in 'Subsistema ALM\UTFrmCotizador.pas' {FrmCotizador},
  UTFrmCotizadorCompara in 'Subsistema ALM\UTFrmCotizadorCompara.pas' {frmCotizadorCompara},
  UTFrmDatosAlmacen in 'Subsistema ALM\UTFrmDatosAlmacen.pas' {FrmDatosAlmacen},
  UTFrmDatosArticulo in 'Subsistema ALM\UTFrmDatosArticulo.pas' {FrmDatosArticulo},
  UTFrmDatosFormaPago in 'Subsistema ALM\UTFrmDatosFormaPago.pas' {FrmDatosFormaPago},
  UTFrmDatosProveedores in 'Subsistema ALM\UTFrmDatosProveedores.pas' {FrmDatosProveedores},
  UTFrmDatosViaEmbarque in 'Subsistema ALM\UTFrmDatosViaEmbarque.pas' {FrmDatosViaEmbarque},
  UTFrmDevolucionIndividualIns in 'Subsistema ALM\UTFrmDevolucionIndividualIns.pas' {FrmDevolucionIndividualIns},
  UTFrmEntradaPartida in 'Subsistema ALM\UTFrmEntradaPartida.pas' {FrmEntradaPartida},
  UTFrmEntradas in 'Subsistema ALM\UTFrmEntradas.pas' {FrmEntradas},
  UTFrmEntradasDetalle in 'Subsistema ALM\UTFrmEntradasDetalle.pas' {FrmEntradasDetalle},
  UTFrmEntradasXOCDetalle in 'Subsistema ALM\UTFrmEntradasXOCDetalle.pas' {FrmEntradasXOCDetalle},
  UTFrmEntradaXOC in 'Subsistema ALM\UTFrmEntradaXOC.pas' {FrmEntradaXOC},
  UTFrmEntradaXOCPartida in 'Subsistema ALM\UTFrmEntradaXOCPartida.pas' {FrmEntradaXOCPartida},
  UTFrmEntradaXOCPartidaAdd in 'Subsistema ALM\UTFrmEntradaXOCPartidaAdd.pas' {FrmEntradaXOCPartidaAdd},
  UTFrmExistenciaArticulo in 'Subsistema ALM\UTFrmExistenciaArticulo.pas' {frmExistenciaArticulo},
  UTFrmInventario in 'Subsistema ALM\UTFrmInventario.pas' {FrmInventario},
  UTFrmInventarioDetalle in 'Subsistema ALM\UTFrmInventarioDetalle.pas' {FrmInventarioDetalle},
  UTFrmOrdenCompra in 'Subsistema ALM\UTFrmOrdenCompra.pas' {FrmOrdenCompra},
  UTFrmOrdenCompraDetalle in 'Subsistema ALM\UTFrmOrdenCompraDetalle.pas' {FrmOrdenCompraDetalle},
  UTFrmOrdenCompraEntrada in 'Subsistema ALM\UTFrmOrdenCompraEntrada.pas' {FrmOrdenCompraEntrada},
  UTFrmPartidaExis in 'Subsistema ALM\UTFrmPartidaExis.pas' {FrmPartidaExis},
  UTFrmProveedores in 'Subsistema ALM\UTFrmProveedores.pas' {FrmProveedores},
  UtfrmRepInventario in 'Subsistema ALM\UtfrmRepInventario.pas' {FrmRepInventario},
  UTfrmReporteCotizacionSinEntrada in 'Subsistema ALM\UTfrmReporteCotizacionSinEntrada.pas' {FrmReporteCotSinEnt},
  UTfrmReporteCotizacionSinOC in 'Subsistema ALM\UTfrmReporteCotizacionSinOC.pas' {FrmReporteCotSinOC},
  UTfrmReporteMaterialNoCotizado in 'Subsistema ALM\UTfrmReporteMaterialNoCotizado.pas' {FrmReporteMatNoCot},
  UTfrmReporteMaterialNoValidado in 'Subsistema ALM\UTfrmReporteMaterialNoValidado.pas' {FrmReporteMatNoVal},
  UTfrmReporteMaterialSinEntrada in 'Subsistema ALM\UTfrmReporteMaterialSinEntrada.pas' {FrmReporteMatSinEnt},
  UTfrmReporteMaterialSinOC in 'Subsistema ALM\UTfrmReporteMaterialSinOC.pas' {FrmReporteMatSinOC},
  UTfrmReporteOCSinEntrada in 'Subsistema ALM\UTfrmReporteOCSinEntrada.pas' {FrmReporteOCSinEnt},
  UTFrmReportesGenerales in 'Subsistema ALM\UTFrmReportesGenerales.pas' {FrmReportesGenerales},
  UTFrmRequisicionDetalle in 'Subsistema ALM\UTFrmRequisicionDetalle.pas' {FrmRequisicionDetalle},
  UTFrmRequisiciones in 'Subsistema ALM\UTFrmRequisiciones.pas' {FrmRequisiciones},
  UTFrmRequisicionPartida in 'Subsistema ALM\UTFrmRequisicionPartida.pas' {FrmRequisicionPartida},
  UTFrmSalidaDetalle in 'Subsistema ALM\UTFrmSalidaDetalle.pas' {FrmSalidaDetalle},
  UTFrmSalidaDetalle2 in 'Subsistema ALM\UTFrmSalidaDetalle2.pas' {FrmSalidaDetalle2},
  UTFrmSalidaManDetalle in 'Subsistema ALM\UTFrmSalidaManDetalle.pas' {FrmSalidaManDetalle},
  UTFrmSalidaManifiesto in 'Subsistema ALM\UTFrmSalidaManifiesto.pas' {FrmSalidaManifiesto},
  UTFrmSalidaManifiestoDetalle in 'Subsistema ALM\UTFrmSalidaManifiestoDetalle.pas' {FrmSalidaManifiestoDetalle},
  UTFrmSalidaManifiestoPartida in 'Subsistema ALM\UTFrmSalidaManifiestoPartida.pas' {FrmSalidaManifiestoPartida},
  UTFrmSalidaManPartida in 'Subsistema ALM\UTFrmSalidaManPartida.pas' {FrmSalidaManPartida},
  UTFrmSalidaPartida in 'Subsistema ALM\UTFrmSalidaPartida.pas' {FrmSalidaPartida},
  UTFrmSalidaPartidaDist in 'Subsistema ALM\UTFrmSalidaPartidaDist.pas' {FrmSalidaPartidaDist},
  UTFrmSalidas in 'Subsistema ALM\UTFrmSalidas.pas' {FrmSalidas},
  UTFrmSalidasMan in 'Subsistema ALM\UTFrmSalidasMan.pas' {FrmSalidasMan},
  UTFrmSalidaSolDetalle in 'Subsistema ALM\UTFrmSalidaSolDetalle.pas' {FrmSalidaSolDetalle},
  UTFrmSeguimiento in 'Subsistema ALM\UTFrmSeguimiento.pas' {FrmSeguimiento},
  UTFrmSelArticulo in 'Subsistema ALM\UTFrmSelArticulo.pas' {FrmSelArticulo},
  UTFrmSelecControlLog in 'Subsistema ALM\UTFrmSelecControlLog.pas' {FrmControlLog},
  UTFrmSolicitudDetalle in 'Subsistema ALM\UTFrmSolicitudDetalle.pas' {FrmSolicitudDetalle},
  UTFrmSolicitudes in 'Subsistema ALM\UTFrmSolicitudes.pas' {FrmSolicitudes},
  UTFrmSolicitudesAC in 'Subsistema ALM\UTFrmSolicitudesAC.pas' {FrmSolicitudesAC},
  UTFrmSolicitudesAP in 'Subsistema ALM\UTFrmSolicitudesAP.pas' {FrmSolicitudesAP},
  UTFrmSolicitudesSurtir in 'Subsistema ALM\UTFrmSolicitudesSurtir.pas' {FrmSolicitudesSurtir},
  UTFrmSolicitudPartida in 'Subsistema ALM\UTFrmSolicitudPartida.pas' {FrmSolicitudPartida},
  UTFrmSolicitudSalidaDet in 'Subsistema ALM\UTFrmSolicitudSalidaDet.pas' {FrmSolicitudSalidaDet},
  UTFrmValidacionSDetalle in 'Subsistema ALM\UTFrmValidacionSDetalle.pas' {FrmValidacionSDetalle},
  UTFrmValidacionSolicitud in 'Subsistema ALM\UTFrmValidacionSolicitud.pas' {FrmValidacionSolicitud},
  UTFrmVerificacionSDetalle in 'Subsistema ALM\UTFrmVerificacionSDetalle.pas' {FrmVerificacionSDetalle},
  UTFrmVerificacionSolicitud in 'Subsistema ALM\UTFrmVerificacionSolicitud.pas' {FrmVerificacionSolicitud},
  UTFrmViaEmbarque in 'Subsistema ALM\UTFrmViaEmbarque.pas' {FrmViaEmbarque},
  UTFrmPostCorreo in 'UTFrmPostCorreo.pas' {FrmPostCorreo},
  UTFrmCuentasCorreo in 'UTFrmCuentasCorreo.pas' {FrmCuentasCorreo},
  UTFrmBusquedaDetallexEntrada in 'Subsistema TIC\UTFrmBusquedaDetallexEntrada.pas' {FrmBusquedaDetallexEntrada},
  UTfrmDetalleXEntrada in 'Subsistema TIC\UTfrmDetalleXEntrada.pas' {FrmDetalleXEntrada},
  UTFrmCargos in 'Subsistema RHH\UTFrmCargos.pas' {FrmCargos},
  UTFrmDatosCargo in 'Subsistema RHH\UTFrmDatosCargo.pas' {FrmDatosCargo},
  UnitTIniTracer in 'UnitTIniTracer.pas',
  frm_CifraIni in 'frm_CifraIni.pas' {FrmCifraIni},
  global in 'global.pas',
  frm_connection in 'frm_connection.pas' {connection: TDataModule},
  Utilerias in 'Utilerias.pas',
  StoHtmlHelp in 'StoHtmlHelp.pas',
  UnitExcepciones in 'UnitExcepciones.pas',
  unitmanejofondo in 'unitmanejofondo.pas',
  frm_AltaServidor in 'frm_AltaServidor.pas' {frmAltaServidor},
  frm_PendientesNew in 'frm_PendientesNew.pas' {frmPendientesNew},
  UFunctionsGHH in 'UFunctionsGHH.pas',
  UnitValidacion in 'UnitValidacion.pas',
  frm_barra in 'frm_barra.pas' {frmBarra: TFrame},
  UDbGrid in 'UDbGrid.pas',
  UnitTBotonesPermisos in 'UnitTBotonesPermisos.pas',
  UnitValidaTexto in 'UnitValidaTexto.pas',
  UnitExcel in 'UnitExcel.pas',
  unitActivaPop in 'unitActivaPop.pas',
  UnitTablasImpactadas in 'UnitTablasImpactadas.pas',
  USelCol in 'USelCol.pas' {frmColumnas},
  UTFrmTablaISPTAnual in 'Subsistema RHH\UTFrmTablaISPTAnual.pas' {FrmTablaISPTAnual},
  UTFrmSubsidioTablaISPT in 'Subsistema RHH\UTFrmSubsidioTablaISPT.pas' {FrmSubsidioTablaISPT},
  UTFrmRangoSalarios in 'Subsistema RHH\UTFrmRangoSalarios.pas' {FrmRangoSalarios},
  UTFrmTipoNomina in 'Subsistema RHH\UTFrmTipoNomina.pas' {FrmTipoNomina},
  UTFrmTablaIMSS in 'Subsistema RHH\UTFrmTablaIMSS.pas' {FrmTablaIMSS},
  UTFrmNominas in 'Subsistema RHH\UTFrmNominas.pas' {FrmNominas},
  UTFrmProyeccionNomina in 'Subsistema RHH\UTFrmProyeccionNomina.pas' {FrmProyeccionNomina},
  UTFrmTipoInasistencia in 'Subsistema RHH\UTFrmTipoInasistencia.pas' {FrmTipoInasistencia},
  UTFrmPrestaciones in 'Subsistema RHH\UTFrmPrestaciones.pas' {FrmPrestaciones},
  UTFrmConceptosNomina in 'Subsistema RHH\UTFrmConceptosNomina.pas' {FrmConceptosNomina},
  UTFrmDatosConceptosNomina in 'Subsistema RHH\UTFrmDatosConceptosNomina.pas' {FrmDatosConceptosNomina},
  UTFrmGuardia in 'Subsistema RHH\UTFrmGuardia.pas' {FrmGuardia},
  UTFrmDatosGuardia in 'Subsistema RHH\UTFrmDatosGuardia.pas' {FrmDatosGuardia},
  UTFrmPeriodoGuardia in 'Subsistema RHH\UTFrmPeriodoGuardia.pas' {FrmPeriodoGuardia},
  UTFrmDatosConceptoExtra in 'Subsistema RHH\UTFrmDatosConceptoExtra.pas' {FrmDatosConceptoExtra},
  UTFrmDatosConExtrasXEmpleado in 'Subsistema RHH\UTFrmDatosConExtrasXEmpleado.pas' {FrmDatosConExtrasXEmpleado},
  UTFrmConceptosExtras in 'Subsistema RHH\UTFrmConceptosExtras.pas' {FrmConceptosExtras},
  UTFrmCatalogoPostulantes in 'Subsistema RHH\UTFrmCatalogoPostulantes.pas' {FrmCatalogoPostulantes},
  UTFrmPersonal in 'UTFrmPersonal.pas' {FrmPersonal},
  UTFrmPostulante in 'Subsistema RHH\UTFrmPostulante.pas' {FrmPostulante},
  UTFrmNuevaPlazaParaPersonal in 'Subsistema RHH\UTFrmNuevaPlazaParaPersonal.pas' {FrmNuevaPlazaParaPersonal},
  UCalculoNomina in 'Subsistema RHH\UCalculoNomina.pas',
  UTFrmReporteAcumuladoGlob in 'Subsistema RHH\UTFrmReporteAcumuladoGlob.pas' {FrmReporteAcumuladoGlob},
  UTFrmVacaciones in 'Subsistema RHH\UTFrmVacaciones.pas' {FrmVacaciones},
  UTFrmDiasFestivos in 'Subsistema RHH\UTFrmDiasFestivos.pas' {FrmDiasFestivos},
  UTFrmCatalogoSalarios in 'Subsistema RHH\UTFrmCatalogoSalarios.pas' {FrmCatalogoSalarios},
  UTFrmExcepciones in 'Subsistema RHH\UTFrmExcepciones.pas' {FrmExcepciones},
  UTFrmPersonalNomina in 'Subsistema RHH\UTFrmPersonalNomina.pas' {FrmPersonalNomina},
  UTFrmCatalogoNominas in 'Subsistema RHH\UTFrmCatalogoNominas.pas' {FrmCatalogoNominas},
  UTFrmAbrirNomina in 'Subsistema RHH\UTFrmAbrirNomina.pas' {FrmAbrirNomina},
  UTFrmPagoNomina in 'Subsistema RHH\UTFrmPagoNomina.pas' {FrmPagoNomina},
  UTFrmSeleccionSalMultiple in 'Subsistema RHH\UTFrmSeleccionSalMultiple.pas' {FrmSeleccionSalMultiple},
  UTFrmFichaPersonalDX in 'Subsistema RHH\UTFrmFichaPersonalDX.pas' {FrmFichaPersonalDX},
  UTFrmMaestroPersonal in 'Subsistema RHH\UTFrmMaestroPersonal.pas' {FrmMaestroPersonal},
  UTFrmModificarImportesNomina in 'Subsistema RHH\UTFrmModificarImportesNomina.pas' {FrmModificarImportesNomina},
  UTfrmContratoPersonalDetalle in 'Subsistema RHH\UTfrmContratoPersonalDetalle.pas' {FrmContratoPersonalDetalle},
  UTFrmSubsidioTablaISPT_Anual in 'Subsistema RHH\UTFrmSubsidioTablaISPT_Anual.pas' {FrmSubsidioTablaISPT_Anual},
  UTFrmExcepcionesEspeciales in 'Subsistema RHH\UTFrmExcepcionesEspeciales.pas' {FrmExcepcionesEspeciales},
  UTFrmSeleccionaSalario in 'Subsistema RHH\UTFrmSeleccionaSalario.pas' {FrmSeleccionaSalario},
  UTFrmTablaISPT in 'Subsistema RHH\UTFrmTablaISPT.pas' {FrmTablaISPT},
  UTFrmTablaSubsidioISPTAnual in 'Subsistema RHH\UTFrmTablaSubsidioISPTAnual.pas' {FrmTablaSubsidioISPTAnual},
  UTFrmAsignarHorasExtras in 'Subsistema RHH\UTFrmAsignarHorasExtras.pas' {FrmAsignarHorasExtras},
  UTFrmPersonalContrato in 'Subsistema RHH\UTFrmPersonalContrato.pas' {FrmPersonalContrato},
  UTFrmContratoPersonal in 'Subsistema RHH\UTFrmContratoPersonal.pas' {FrmContratoPersonal},
  UTFrmContratarWizard in 'Subsistema RHH\UTFrmContratarWizard.pas' {FrmContratarWizard},
  UTFrmBajasFijos in 'Subsistema RHH\UTFrmBajasFijos.pas' {FrmBajasFijos},
  UtfrmModificaPersonalImss in 'Subsistema RHH\UtfrmModificaPersonalImss.pas' {FrmModificaPersonalImss},
  AcroPDFLib_TLB in 'D:\RAD Studio\8.0\Imports\AcroPDFLib_TLB.pas',
  UTFrmPersonalHExtra in 'Subsistema RHH\UTFrmPersonalHExtra.pas' {FrmPersonalHExtra},
  UTFrmConcentradoNomina in 'Subsistema RHH\UTFrmConcentradoNomina.pas' {FrmConcentradoNomina},
  UTFrmConsultaPagos in 'Subsistema RHH\UTFrmConsultaPagos.pas' {FrmConsultaPagos},
  UtFrmfrmConceptoExtraEmpleado in 'Subsistema RHH\UtFrmfrmConceptoExtraEmpleado.pas' {frmConceptoExtraEmpleado},
  UtfrmComparaRhNomina in 'Subsistema RHH\UtfrmComparaRhNomina.pas' {FrmComparaRhNomina},
  UtFrmModificarPago in 'Subsistema RHH\UtFrmModificarPago.pas' {frmModificarPago},
  UtfrmCatalogoConceptosExtras in 'Subsistema RHH\UtfrmCatalogoConceptosExtras.pas' {frmCatalogoConceptosExtras},
  UtFrmCatalogoSalarios2 in 'Subsistema RHH\UtFrmCatalogoSalarios2.pas' {FrmCatalogoSalarios2},
  UtfrmKardex in 'Subsistema RHH\UtfrmKardex.pas' {frmKardex},
  UtFrmHistorialPago in 'Subsistema RHH\UtFrmHistorialPago.pas' {FrmHistorialPago},
  UTFrmFirmantesExcepciones in 'Subsistema RHH\UTFrmFirmantesExcepciones.pas' {FrmFirmantesExcepciones},
  UTFrmFirmantesSolicitantes in 'Subsistema RHH\UTFrmFirmantesSolicitantes.pas' {FrmFirmantesSolicitantes},
  UTFrmFirmantesSolicitantesUpt in 'Subsistema RHH\UTFrmFirmantesSolicitantesUpt.pas' {FrmFirmantesSolicitantesUpt},
  UTFrmPlazaRhuDX in 'Subsistema RHH\UTFrmPlazaRhuDX.pas' {FrmPlazaRhuDX},
  UTFrmAsignarPostulantes in 'Subsistema RHH\UTFrmAsignarPostulantes.pas' {FrmAsignarPostulantes},
  UTFrmPlazaGeneral in 'Subsistema RHH\UTFrmPlazaGeneral.pas' {FrmPlazaGeneral},
  UTFrmSeleccionarPlaza in 'Subsistema RHH\UTFrmSeleccionarPlaza.pas' {FrmSeleccionarPlaza},
  UTFrmSeleccionarCargo in 'Subsistema RHH\UTFrmSeleccionarCargo.pas' {FrmSeleccionarCargo},
  UTFrmDiasPTU in 'Subsistema RHH\UTFrmDiasPTU.pas' {FrmDiasPtu},
  UTFRMDatosContratacion in 'Subsistema RHH\UTFRMDatosContratacion.pas' {FrmDatosContratacion},
  UtFrmFichaGeneralPersonal in 'Subsistema RHH\UtFrmFichaGeneralPersonal.pas' {FrmFichaGeneralPersonal},
  UTFrmHorarios in 'Subsistema RHH\UTFrmHorarios.pas' {FrmHorarios},
  UTFrmNominasExcel in 'Subsistema RHH\UTFrmNominasExcel.pas' {FrmNominasExcel},
  UtFrmWizardReporteExcel in 'Subsistema RHH\UtFrmWizardReporteExcel.pas' {FrmWizardReporteExcel},
  UTFrmPlantillaBancaria in 'Subsistema RHH\UTFrmPlantillaBancaria.pas' {FrmPlantillaBancaria},
  UTFrmReporteInsidencias in 'Subsistema RHH\UTFrmReporteInsidencias.pas' {FrmReporteInsidencias},
  UtfrmGastos in 'Subsistema CONT\UtfrmGastos.pas' {FrmGastos},
  UTFrmConsultaFichaPersonal in 'Subsistema RHH\UTFrmConsultaFichaPersonal.pas' {FrmConsultaFichaPersonal},
  UTFrmCalculoSalario in 'Subsistema RHH\UTFrmCalculoSalario.pas' {FrmCalculoSalario},
  QuricolCode in 'xml\GeneradorCBB\QuricolCode.pas',
  QuricolAPI in 'xml\GeneradorCBB\QuricolAPI.pas',
  GeneradorCBB in 'xml\GeneradorCBB\GeneradorCBB.pas',
  PFacturaElectronica in 'xml\PFacturaElectronica.pas',
  PACFo in 'xml\PAC\FO\PACFo.pas',
  PFacturaElectronica_Reglamentaciones in 'xml\PFacturaElectronica_Reglamentaciones.pas',
  PFacturaElectronica_PAC in 'xml\PFacturaElectronica_PAC.pas',
  wsFO in 'xml\PAC\FO\wsFO.pas',
  CFDI in 'xml\CFDI.pas',
  SelloDigital in 'xml\GeneradorSello\SelloDigital.pas',
  ClaseOpenSSL in 'xml\GeneradorSello\ClaseOpenSSL.pas',
  libeay32 in 'xml\GeneradorSello\libeay32.pas',
  LibEay32Plus in 'xml\GeneradorSello\LibEay32Plus.pas',
  OpenSSLUtils in 'xml\GeneradorSello\OpenSSLUtils.pas',
  ClaseCertificadoSellos in 'xml\GeneradorSello\ClaseCertificadoSellos.pas',
  UTFrmEditarDetalle in 'Subsistema RHH\UTFrmEditarDetalle.pas' {FrmEditarDetalle},
  UTFrmSeleccionarDepartamento in 'Subsistema RHH\UTFrmSeleccionarDepartamento.pas' {FrmSeleccionarDepartamento},
  UTFrmSeleccionaSolicitante in 'Subsistema RHH\UTFrmSeleccionaSolicitante.pas' {FrmSeleccionaSolicitante},
  UtFrmContratacionPersonal in 'Subsistema RHH\UtFrmContratacionPersonal.pas' {FrmContratacionPersonal},
  UTFrmCalculoVacAguin in 'Subsistema RHH\UTFrmCalculoVacAguin.pas' {FrmCalculoVacAguin},
  UTFrmCapturaRetardos in 'Subsistema RHH\UTFrmCapturaRetardos.pas' {FrmCapturaRetardos},
  UTFrmConcentradoPTU in 'Subsistema RHH\UTFrmConcentradoPTU.pas' {FrmConcentradoPTU},
  UTFrmDeptos in 'Subsistema RHH\UTFrmDeptos.pas' {FrmDeptos},
  UTFrmGruposSalarios in 'Subsistema RHH\UTFrmGruposSalarios.pas' {FrmGruposSalarios},
  UTFrmSueldosSalarios in 'Subsistema RHH\UTFrmSueldosSalarios.pas' {FrmSueldosSalarios},
  UTFrmTablaFactoresIntegracion in 'Subsistema RHH\UTFrmTablaFactoresIntegracion.pas' {FrmTablaFactoresIntegracion},
  UTFrmCatalogoPersonalDEX in 'Subsistema RHH\UTFrmCatalogoPersonalDEX.pas' {FrmCatalogoPersonalDEX},
  UTFrmMachotes in 'Subsistema RHH\UTFrmMachotes.pas' {FrmMachotes},
  UTFrmRegistroGastos in 'Subsistema RHH\UTFrmRegistroGastos.pas' {FrmRegistroGastos},
  UTFrmAntiguedadVacaciones in 'Subsistema RHH\UTFrmAntiguedadVacaciones.pas' {FrmAntiguedadVacaciones},
  UtfrmOrganizaciones in 'Subsistema RHH\UtfrmOrganizaciones.pas' {FrmOrganizaciones},
  UTFrmMaestroCuentasContables in 'Subsistema CONT\UTFrmMaestroCuentasContables.pas' {FrmMaestroCuentasContables},
  UtFrmUsuariosSistema in 'UtFrmUsuariosSistema.pas' {FrmUsuariosSistema},
  UTFrmUtilidades in 'Subsistema RHH\UTFrmUtilidades.pas' {FrmUtilidades},
  UTFrmCuentasBanco in 'Subsistema CONT\UTFrmCuentasBanco.pas' {FrmCuentasBanco},
  UTFrmSU in 'UTFrmSU.pas' {FrmSu},
  FrmEstadosDeTimbres in 'FrmEstadosDeTimbres.pas' {TFrmEstadosDeTimbres},
  UTFrmReportesPersonalizados in 'UTFrmReportesPersonalizados.pas' {FrmReportesPersonalizados},
  UTFrmListaNominaExcel in 'Subsistema RHH\UTFrmListaNominaExcel.pas' {FrmListaNominasExcel},
  UTFrmDisenoReporte in 'UTFrmDisenoReporte.pas' {FrmDisenoReporte},
  UtFrmConfiguracionAcceso in 'Configuracion\UtFrmConfiguracionAcceso.pas' {frmConfiguracionAcceso},
  UInteliDialog in 'Comunes Intelicode\UInteliDialog.pas' {InteliDialog},
  UTFrmCorteNominas in 'Subsistema RHH\UTFrmCorteNominas.pas' {FrmCorteNominas},
  UTFrmFormatoEmbarcados in 'UTFrmFormatoEmbarcados.pas' {FrmFormatosEmbarcados},
  UTFrmFirmantesExcel in 'UTFrmFirmantesExcel.pas' {FrmFirmantesExcel},
  UTFrmDoctosxCargo in 'Subsistema RHH\UTFrmDoctosxCargo.pas' {FrmDoctosxCargo},
  UTFrmFormatosExcel in 'UTFrmFormatosExcel.pas' {FrmFormatosExcel},
  UTFrmAnalisisPostulantes in 'Subsistema RHH\UTFrmAnalisisPostulantes.pas' {FrmAnalisisPostulantes},
  UTFrmPresentaAnalisis in 'Subsistema RHH\UTFrmPresentaAnalisis.pas' {FrmPresentaAnalisis},
  UTFrmContratacionPersonalDX in 'Subsistema RHH\UTFrmContratacionPersonalDX.pas' {FrmContratacionPersonalDX},
  UTFrmSelGrupos in 'Subsistema RHH\UTFrmSelGrupos.pas' {FrmSelGrupos},
  UTFrmSelDocumentos in 'Subsistema RHH\UTFrmSelDocumentos.pas' {FrmSelDocumentos},
  UTFrmReportesExcel in 'UTFrmReportesExcel.pas' {FrmNominasAnualExcel},
  UtfrmDimm in 'Subsistema RHH\UtfrmDimm.pas' {FrmDimm},
  UTFrmConsultaVacaciones in 'Subsistema RHH\UTFrmConsultaVacaciones.pas' {FrmConsultaVacaciones},
  ExBar in 'Comunes Intelicode\ExBar.pas',
  ExBarClasses in 'Comunes Intelicode\ExBarClasses.pas',
  URegistro in 'Comunes Intelicode\URegistro.pas';

(*  UTFrmEditUsuario in 'UTFrmEditUsuario.pas' {FrmEditUsuario},
  frm_CatalogoUsuarios in 'frm_CatalogoUsuarios.pas' {frmCatalogoUsuarios},
  frm_addRow_CatalogoUsuarios in 'frm_addRow_CatalogoUsuarios.pas' {frmAddRowCatalogoUsuarios},
  frm_addRow_CatalogoRoles in 'frm_addRow_CatalogoRoles.pas' {frmAddRowCatalogoRoles},
  frm_CatalogoRoles in 'frm_CatalogoRoles.pas' {frmCatalogoRoles},
  frm_addRow_CatalogoDepartamentos in 'frm_addRow_CatalogoDepartamentos.pas' {frmAddRowCatalogoDepartamentos},
  frm_CatalogoDepartamentos in 'frm_CatalogoDepartamentos.pas' {frmCatalogoDepartamentos},
  frm_CatalogoRegistros in 'frm_CatalogoRegistros.pas' {frmCatalogoRegistros},
  frm_addRow_CatalogoRegistros in 'frm_addRow_CatalogoRegistros.pas' {frmAddRowCatalogoRegistros},
  frm_Login in 'frm_Login.pas' {frmLogin},
  Unit1 in 'Unit1.pas' {TMSFrame1: TFrame},
  Unit2_ in 'Unit2_.pas' {frm_Principal},
  Frm_Frentes in 'Frm_Frentes.pas' {FrmFrentes},
  Frm_AddRowFrente in 'Frm_AddRowFrente.pas' {FrmAddRowFrente},
  frm_Monedas in 'frm_Monedas.pas' {frmMonedas},
  Frm_AddRowMoneda in 'Frm_AddRowMoneda.pas' {FrmAddRowMoneda},
  Frm_ConversionMoneda in 'Frm_ConversionMoneda.pas' {FrmConversionMoneda},
  Frm_AddRowConversionMoneda in 'Frm_AddRowConversionMoneda.pas' {FrmAddRowConversionMoneda},
  Frm_CatalogoExcepciones in 'Frm_CatalogoExcepciones.pas' {FrmCatalogoExcepciones},
  Frm_ExcepcionFecha in 'Frm_ExcepcionFecha.pas' {FrmExcepcionFecha},
  Frm_AddRowExcepcionFecha in 'Frm_AddRowExcepcionFecha.pas' {FrmAddRowExcepcionFecha},
  Frm_ConversionUnidad in 'Frm_ConversionUnidad.pas' {FrmConversionUnidad},
  Frm_Unidades in 'Frm_Unidades.pas' {FrmUnidades},
  Frm_AddRowPruebaConcepto in 'Frm_AddRowPruebaConcepto.pas' {FrmAddRowPruebaConcepto},
  Frm_Embarcaciones in 'Frm_Embarcaciones.pas' {FrmEmbarcaciones},
  Temporizador in 'Temporizador.pas',
  Frm_Contratos in 'Frm_Contratos.pas' {FrmContratos},
  Frm_AddRowContratos in 'Frm_AddRowContratos.pas' {FrmAddRowContratos};*)

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.Title := 'Sistema de Nóminas';
  Application.CreateForm(TForm2, Form2);
  Application.CreateForm(TClientModule1, ClientModule1);
  Application.CreateForm(TFrmSuite, FrmSuite);
  Application.CreateForm(TInfoPanel, InfoPanel);
  Application.CreateForm(TInteliDialog, InteliDialog);
  Application.Run;
end.
